package tpfinal.login.welcome;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import tpfinal.graficos.Icono;
import tpfinal.vistas.AdministrarVentanas;
import tpfinal.vistas.VentanaJuego;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * Clase que crea la ventana de Bienvenida al juego.
 */
public class Welcomepage implements VentanaJuego {
    private JPanel jPanelPpal;
    private JButton botonRegistrarse;
    private JButton botonLogin;
    private JLabel imagenFondo;
    private JFrame jFramePpal;

    /**
     * El constructor le da forma a la ventana JFrame, setea los atributos de la misma.
     * Asigna la tipografia a los JLabel.
     * Le asigna a los botones del formulario un listener que va a detectar el click y ejecutar
     * los metodos correspondientes.
     */
    public Welcomepage() {
        jFramePpal = new JFrame("ENCHANTED LAND");
        $$$setupUI$$$();
        jFramePpal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jFramePpal.setPreferredSize(new Dimension(850, 720));
        jFramePpal.setResizable(true);
        jFramePpal.add(jPanelPpal);
        jFramePpal.pack();
        jFramePpal.setLocationRelativeTo(null);
        jFramePpal.setVisible(true);
        ImageIcon icon = Icono.crearIcono();
        jFramePpal.setIconImage(icon.getImage());

        //FUNCION DE REGISTRAR
        botonLogin.addActionListener(clickBotonRegistro());

        //FUNCION DE INICIAR SESION
        botonRegistrarse.addActionListener(clickBotonLogin());
    }

    /**
     * Listener del boton Registrarse.
     *
     * @return ActionListener para el boton asociado.
     */
    private ActionListener clickBotonRegistro() {
        return e -> {
            jFramePpal.dispose();
            AdministrarVentanas.iniciarVentanaRegistro();
            AdministrarVentanas.cambiarEstadoActual(8);
        };
    }

    /**
     * Listener del boton Login.
     *
     * @return ActionListener para el boton asociado.
     */
    private ActionListener clickBotonLogin() {
        return e -> {
            jFramePpal.dispose();
            AdministrarVentanas.iniciarVentanaLogin();
            AdministrarVentanas.cambiarEstadoActual(9);
        };
    }

    @Override
    public void actualizar() {
    }

    @Override
    public void dibujar(Graphics grafico) {
    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanelPpal = new JPanel();
        jPanelPpal.setLayout(new GridLayoutManager(5, 6, new Insets(0, 0, 0, 0), -1, -1));
        jPanelPpal.setBackground(new Color(-16777216));
        botonLogin = new JButton();
        botonLogin.setBorderPainted(false);
        botonLogin.setContentAreaFilled(false);
        botonLogin.setFocusPainted(false);
        botonLogin.setHorizontalTextPosition(0);
        botonLogin.setIcon(new ImageIcon(getClass().getResource("/Login/imagenes/botonRegister.png")));
        botonLogin.setLabel("");
        botonLogin.setText("");
        jPanelPpal.add(botonLogin, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 4, false));
        final Spacer spacer1 = new Spacer();
        jPanelPpal.add(spacer1, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        jPanelPpal.add(spacer2, new GridConstraints(0, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        jPanelPpal.add(spacer3, new GridConstraints(4, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        jPanelPpal.add(spacer4, new GridConstraints(4, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        jPanelPpal.add(spacer5, new GridConstraints(2, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer6 = new Spacer();
        jPanelPpal.add(spacer6, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer7 = new Spacer();
        jPanelPpal.add(spacer7, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer8 = new Spacer();
        jPanelPpal.add(spacer8, new GridConstraints(1, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        imagenFondo = new JLabel();
        imagenFondo.setIcon(new ImageIcon(getClass().getResource("/Login/imagenes/portada.png")));
        imagenFondo.setText("");
        jPanelPpal.add(imagenFondo, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        botonRegistrarse = new JButton();
        botonRegistrarse.setBorderPainted(false);
        botonRegistrarse.setContentAreaFilled(false);
        botonRegistrarse.setEnabled(true);
        botonRegistrarse.setFocusPainted(false);
        botonRegistrarse.setHorizontalTextPosition(0);
        botonRegistrarse.setIcon(new ImageIcon(getClass().getResource("/Login/imagenes/botonEnter.png")));
        botonRegistrarse.setText("");
        jPanelPpal.add(botonRegistrarse, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanelPpal;
    }

}